"""Implementando Leitura

Revision ID: 2a8423e56088
Revises: e6631ab9e9aa
Create Date: 2025-10-13 22:56:20.845206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8423e56088'
down_revision = 'e6631ab9e9aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leitura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('propriedade_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tanque',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.Column('id_propriedade', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('area_tanque', sa.Float(), nullable=False),
    sa.Column('tipo_peixe', sa.String(length=50), nullable=False),
    sa.Column('peso_peixe', sa.Float(), nullable=True),
    sa.Column('qtd_peixe', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_propriedade'], ['propriedade.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tanque')
    op.drop_table('leitura')
    # ### end Alembic commands ###
