"""perfil local removido

Revision ID: 5146e522c6a9
Revises: 9d986dc3dc36
Create Date: 2025-09-02 20:28:39.046535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5146e522c6a9'
down_revision = '9d986dc3dc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propriedade_perfil')
    with op.batch_alter_table('propriedade_usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('propriedade_usuarios_perfil_local_fkey'), type_='foreignkey')
        batch_op.drop_column('perfil_local')

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('propriedade_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['usuario_id'])
        batch_op.create_unique_constraint(None, ['propriedade_id'])
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'propriedade', ['propriedade_id'], ['id'])

    with op.batch_alter_table('turbidez', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proprietario_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'usuario', ['proprietario_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turbidez', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('proprietario_id')

    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('propriedade_id')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('propriedade_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_local', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('propriedade_usuarios_perfil_local_fkey'), 'perfil', ['perfil_local'], ['id'])

    op.create_table('propriedade_perfil',
    sa.Column('propriedade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('perfil_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], name=op.f('propriedade_perfil_perfil_id_fkey')),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], name=op.f('propriedade_perfil_propriedade_id_fkey')),
    sa.PrimaryKeyConstraint('propriedade_id', 'perfil_id', name=op.f('propriedade_perfil_pkey'))
    )
    # ### end Alembic commands ###
