"""Adicionar Proprietario na propriedade

Revision ID: 5d230c78a091
Revises: a932f8012776
Create Date: 2025-04-14 21:38:50.574003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d230c78a091'
down_revision = 'a932f8012776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propriedade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proprietario_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['proprietario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propriedade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proprietario_id')

    # ### end Alembic commands ###
