"""Refactor models for DB independence and validation

Revision ID: 757d1c0dcfb5
Revises: f1c682e18b0c
Create Date: 2026-05-03 16:22:45.240963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '757d1c0dcfb5'
down_revision = 'f1c682e18b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add tanque_id as nullable first to allow data migration
    op.add_column('leitura', sa.Column('tanque_id', sa.Uuid(), nullable=True))
    
    # 2. Copy data from the old 'tanque' column to 'tanque_id'
    op.execute("UPDATE leitura SET tanque_id = tanque")

    with op.batch_alter_table('leitura', schema=None) as batch_op:
        # 3. Now set it to NOT NULL
        batch_op.alter_column('tanque_id', nullable=False)
        
        batch_op.alter_column('turbidez',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('oxigenio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('temperatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('ph',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('amonia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        
        # Handle foreign keys
        # We need to drop the old one and create the new one
        # Note: constraint name might vary, but 'leitura_tanque_fkey' is the default
        batch_op.drop_constraint('leitura_tanque_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tanque', ['tanque_id'], ['id'])
        batch_op.drop_column('tanque')


    # For perfil, Postgres needs an explicit cast from ARRAY to JSON
    op.execute("ALTER TABLE perfil ALTER COLUMN permissoes TYPE JSON USING array_to_json(permissoes)")

    # Data cleanup: Merge duplicate profiles before applying unique constraint
    # 1. Update users to point to the first occurrence of each profile name
    op.execute("""
        UPDATE usuario 
        SET perfil_id = sub.min_id::uuid
        FROM (
            SELECT nome, MIN(id::text) as min_id
            FROM perfil
            GROUP BY nome
        ) AS sub
        JOIN perfil ON perfil.nome = sub.nome
        WHERE usuario.perfil_id = perfil.id
        AND usuario.perfil_id != sub.min_id::uuid;
    """)
    # 2. Delete duplicate profiles
    op.execute("""
        DELETE FROM perfil 
        WHERE id NOT IN (
            SELECT MIN(id::text)::uuid
            FROM perfil 
            GROUP BY nome
        );
    """)


    with op.batch_alter_table('perfil', schema=None) as batch_op:
        # We already handled the type change above, so we just add the unique constraint
        batch_op.create_unique_constraint(None, ['nome'])



    with op.batch_alter_table('tanque', schema=None) as batch_op:
        batch_op.alter_column('area_tanque',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('peso_peixe',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('tanque', schema=None) as batch_op:
        batch_op.alter_column('peso_peixe',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('area_tanque',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('permissoes',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)

    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanque', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leitura_tanque_fkey'), 'tanque', ['tanque'], ['id'])
        batch_op.alter_column('amonia',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('ph',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('temperatura',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('oxigenio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('turbidez',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('tanque_id')

    # ### end Alembic commands ###
