"""Implementa perfil local/global

Revision ID: 9a53e03ef3a2
Revises: 5d230c78a091
Create Date: 2025-05-05 20:46:31.186052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a53e03ef3a2'
down_revision = '5d230c78a091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propriedade_perfil',
    sa.Column('propriedade_id', sa.UUID(), nullable=False),
    sa.Column('perfil_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('propriedade_id', 'perfil_id')
    )
    with op.batch_alter_table('propriedade_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_local', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'perfil', ['perfil_local'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propriedade_usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('perfil_local')

    op.drop_table('propriedade_perfil')
    # ### end Alembic commands ###
