"""Atulização do perfil, variavel de controle

Revision ID: 9d986dc3dc36
Revises: 9a53e03ef3a2
Create Date: 2025-05-11 17:42:27.755557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d986dc3dc36'
down_revision = '9a53e03ef3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('perfil_nome_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.create_unique_constraint('perfil_nome_key', ['nome'])
        batch_op.drop_column('is_global')

    # ### end Alembic commands ###
