"""Adicionada Propriedade

Revision ID: a932f8012776
Revises: 624d2d4d83cd
Create Date: 2025-04-14 20:48:20.627920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a932f8012776'
down_revision = '624d2d4d83cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propriedade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('propriedade_usuarios',
    sa.Column('propriedade_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('propriedade_id', 'usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('propriedade_usuarios')
    op.drop_table('propriedade')
    # ### end Alembic commands ###
