"""Atualiza model Tanque

Revision ID: daa3e4058ab8
Revises: f40bda520ff1
Create Date: 2025-11-17 17:14:38.888877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa3e4058ab8'
down_revision = 'f40bda520ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tanque', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tanque_nome_key'), type_='unique')
        batch_op.create_unique_constraint('uq_tanque_nome_propriedade', ['id_propriedade', 'nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tanque', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tanque_nome_propriedade', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('tanque_nome_key'), ['nome'])

    # ### end Alembic commands ###
