"""Atulização Leitura

Revision ID: f40bda520ff1
Revises: 2a8423e56088
Create Date: 2025-10-13 23:15:34.914073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40bda520ff1'
down_revision = '2a8423e56088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanque', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('turbidez', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('oxigenio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('temperatura', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ph', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('amonia', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('imagem_cor', sa.String(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('leitura_propriedade_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tanque', ['tanque'], ['id'])
        batch_op.drop_column('valor')
        batch_op.drop_column('propriedade_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propriedade_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leitura_propriedade_id_fkey'), 'propriedade', ['propriedade_id'], ['id'])
        batch_op.drop_column('imagem_cor')
        batch_op.drop_column('amonia')
        batch_op.drop_column('ph')
        batch_op.drop_column('temperatura')
        batch_op.drop_column('oxigenio')
        batch_op.drop_column('turbidez')
        batch_op.drop_column('tanque')

    # ### end Alembic commands ###
